INSERT INTO vaccination (name)
VALUES
('Tuberculosis'),
('Rotavirus infection'),
('Diphtheria'),
('Tetanus'),
('Pertussis'),
('Poliomyelitis'),
('Haemophilus influenzae type b infection'),
('Hepatitis B'),
('Pneumococcal disease'),
('Meningococcal disease'),
('Measles'),
('Mumps'),
('Rubella'),
('Varicella'),
('Human papillomavirus infection'),
('Influenza'),
('Herpes zoster'),
('Hepatitis A')